name: geniuspay
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+16

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  web_socket_channel:
  iban: ^1.0.1
  firebase_crashlytics: ^3.0.12
  phone_number: ^0.12.0+2
  firebase_dynamic_links:
  dotted_border: ^2.0.0+2
  share_plus: ^4.0.10
  dropdown_button2:
  flutter_flushbar: ^0.0.2
  cached_network_image: ^3.2.0
  country_icons: ^2.0.2
  crypto: ^3.0.2
  cupertino_icons: ^1.0.2
  currency_icons: ^0.3.0
  equatable: ^2.0.3
  firebase_core: ^2.5.0
  firebase_messaging:
  firebase_remote_config:
  fl_chart: ^0.45.1
  flutter:
    sdk: flutter
  flutter_app_badger: ^1.4.0
  flutter_dotenv:
  flutter_jailbreak_detection: ^1.8.0
  flutter_local_notifications: ^9.3.3
  flutter_svg: ^1.0.0
  geocoding: ^2.0.5
  geolocator:
  get_it: ^7.2.0
  google_fonts: ^2.2.0
  image_picker: ^0.8.4+5
  intl: ^0.17.0
  local_auth: ^1.1.11
  mixpanel_flutter: ^1.0.0
  provider: ^6.0.2
  sentry_flutter: ^6.17.0
  shared_preferences: ^2.0.13
  uuid: ^3.0.6
  veriff_flutter: ^3.0.0
  webview_flutter: ^3.0.1
  gap: ^2.0.0
  intercom_flutter: ^7.2.0
  curved_navigation_bar: ^1.0.3
  ionicons: ^0.1.2
  bubble_tab_indicator: ^0.1.6
  dio: ^4.0.0
  flutter_google_places: ^0.3.0
  google_maps_flutter: ^2.2.3
  # google_maps_flutter: ^2.1.8
  # dio_http_cache: ^0.3.0
  dio_smart_retry: ^1.0.3
  json_annotation: ^4.7.0
  retrofit: ^3.0.0
  retry: ^3.1.0
  location: ^4.4.0
  # connectivity: ^3.0.3
  dartz:
  logger: ^1.1.0
  internet_connection_checker: ^0.0.1+2
  shimmer: ^2.0.0
  flutter_spinkit: ^5.1.0
  #instabug_flutter: ^10.13.0
  device_preview:
  simple_tooltip: ^1.0.0
  flip_card: ^0.6.0
  carousel_slider: ^4.1.1
  app_tracking_transparency: ^2.0.2+4
  syncfusion_flutter_gauges: 20.1.48
  lottie:
  timezone:
  flutter_stripe: ^8.0.0+1
  flutter_staggered_animations:
  screenshot: ^1.3.0
  gallery_saver: ^2.3.2

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  flutter_native_splash: ^1.3.2
  freezed: ^2.3.2
  meta: ^1.8.0
  injectable_generator: ^1.1.2
  json_serializable: ^6.5.4
  objectbox_generator: ^1.1.1
  retrofit_generator: ^3.0.0+2
  build_runner: ^2.0.6
  flutter_test:
    sdk: flutter

dependency_overrides:
  analyzer: ^4.7.0
  crypto: ^3.0.2
  http_parser: ^4.0.2
  json_annotation: ^4.7.0
  json_serializable: ^6.5.4
  meta: ^1.8.0
  path: ^1.8.3
  xml: ^5.4.1
  url_launcher: ^6.1.7

flutter_native_splash:
  color: "#f9f3f1"
  image: assets/images/logo.png
  android: true
  ios: true
  # android_gravity: true
  # ios_content_mode: scaleAspectFill

flutter_icons:
  image_path: assets/icons/launcher_icon.png
  android: true
  ios: true

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/create_categories/
    - assets/icons/profile/refer/
    - assets/icons/profile/points/
    - assets/icons/deposit/
    - assets/icons/home/
    - assets/icons/home/empty_state/
    - assets/icons/home/selected/
    - assets/icons/home/unselected/
    - assets/icons/home/wallet/
    - assets/icons/home/fx/
    - assets/icons/home/more/
    - assets/icons/home/payment/
    - assets/icons/profile/
    - assets/card_items/
    - assets/kyc/
    - assets/onboarding/
    - assets/socials/
    - assets/splash/
    - assets/popups_assets/
    - assets/
    - assets/account/
    - assets/plans/
    - assets/wallets/
    - assets/home/
    - assets/backgrounds/
    - assets/payout/
    - assets/login/
    - assets/transfer/
    - assets/home_designs/
    - assets/faq/
    - assets/share_with_contact/
    - assets/changes_screen/
    - assets/promotions/
    - assets/app_appearance/
    - assets/app_icons/
    - assets/flag_icons/
    - assets/dialogs/
    - assets/customize_cards/
    - assets/create_categories/
    - assets/groups/
    - assets/linked_cards/
    - assets/beneficiary/
    - assets/limits/
    - assets/maintenance/
    - assets/rates_icons/
    - assets/rates/
    - assets/jar/
    - .env
    - assets/insurance/
    - assets/tax/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
